// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDB5Pp2Z_7zbS7aOMo6XD_sdBDALuQ-Tfg',
    appId: '1:1035676093004:web:08da943b709a236d8502e9',
    messagingSenderId: '1035676093004',
    projectId: 'theraportal-a9b26',
    authDomain: 'theraportal-a9b26.firebaseapp.com',
    storageBucket: 'theraportal-a9b26.appspot.com',
    measurementId: 'G-YNV0JTP3SW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRWXhD4S8HLCrULsMWidFlxwBYwnwSLtg',
    appId: '1:1035676093004:android:a9100fff110ef2f98502e9',
    messagingSenderId: '1035676093004',
    projectId: 'theraportal-a9b26',
    storageBucket: 'theraportal-a9b26.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAloUpwnlE0IemEr-TV5FKQYvAaj0hdtAY',
    appId: '1:1035676093004:ios:942089bfa55d807d8502e9',
    messagingSenderId: '1035676093004',
    projectId: 'theraportal-a9b26',
    storageBucket: 'theraportal-a9b26.appspot.com',
    iosBundleId: 'com.example.theraportal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAloUpwnlE0IemEr-TV5FKQYvAaj0hdtAY',
    appId: '1:1035676093004:ios:8df31d6b259e17158502e9',
    messagingSenderId: '1035676093004',
    projectId: 'theraportal-a9b26',
    storageBucket: 'theraportal-a9b26.appspot.com',
    iosBundleId: 'com.example.theraportal.RunnerTests',
  );
}
