class ExerciseConstants {
  static const int numDefaultExercises = 1324;

  static const List<String> uniqueBodyParts = [
    'back',
    'cardio',
    'chest',
    'lower arms',
    'lower legs',
    'neck',
    'shoulders',
    'upper arms',
    'upper legs',
    'waist',
  ];

  static const List<String> uniqueEquipment = [
    'assisted',
    'barbell',
    'band',
    'bosu ball',
    'cable',
    'dumbbell',
    'elliptical machine',
    'ez barbell',
    'hammer',
    'kettlebell',
    'leverage machine',
    'medicine ball',
    'olympic barbell',
    'resistance band',
    'roller',
    'rope',
    'sled machine',
    'skierg machine',
    'smith machine',
    'stability ball',
    'stationary bike',
    'stepmill machine',
    'tire',
    'trap bar',
    'upper body ergometer',
    'weighted',
    'wheel roller',
  ];

  static const List<String> uniqueTargetMuscles = [
    'abductors',
    'abs',
    'adductors',
    'biceps',
    'calves',
    'cardiovascular system',
    'delts',
    'forearms',
    'glutes',
    'hamstrings',
    'lats',
    'levator scapulae',
    'pectorals',
    'quads',
    'serratus anterior',
    'spine',
    'traps',
    'triceps',
    'upper back',
  ];

  static const List<String> uniqueSecondaryMuscles = [
    'abdominals',
    'ankle stabilizers',
    'ankles',
    'back',
    'biceps',
    'brachialis',
    'calves',
    'chest',
    'core',
    'deltoids',
    'feet',
    'forearms',
    'glutes',
    'grip muscles',
    'groin',
    'hands',
    'hamstrings',
    'hip flexors',
    'inner thighs',
    'latissimus dorsi',
    'lower abs',
    'lower back',
    'obliques',
    'quadriceps',
    'rear deltoids',
    'rhomboids',
    'rotator cuff',
    'shins',
    'soleus',
    'sternocleidomastoid',
    'trapezius',
    'traps',
    'triceps',
    'upper back',
    'upper chest',
    'wrists',
    'wrist extensors',
    'wrist flexors',
  ];
}
